export const SAVE_KEY='little-detective.v1';
export const THEMES=[
 {id:0,name:'숲속의 작은 소풍',short:'숲속 소풍',emoji:'🌳',color:'#def2da',ink:'#39744c',desc:'다람쥐 친구들이 기다려요'},
 {id:1,name:'반짝이는 바닷속',short:'바닷속 탐험',emoji:'🐠',color:'#d9effb',ink:'#297394',desc:'산호 사이에 숨은 비밀'},
 {id:2,name:'고양이 빵집',short:'고양이 빵집',emoji:'🥐',color:'#ffe5d0',ink:'#995934',desc:'갓 구운 빵 냄새가 솔솔'},
 {id:3,name:'공룡 친구의 계곡',short:'공룡 계곡',emoji:'🦕',color:'#e5edce',ink:'#6a7a2d',desc:'아주 오래된 친구를 만나요'},
 {id:4,name:'별빛 우주 탐험',short:'우주 여행',emoji:'🚀',color:'#e4ddfa',ink:'#6d56a3',desc:'다음 목적지는 반짝이는 별'},
 {id:5,name:'달콤한 사탕 나라',short:'사탕 나라',emoji:'🍭',color:'#ffe0ec',ink:'#b05a85',desc:'상상보다 더 달콤한 세상'},
 {id:6,name:'햇살 가득 동물 농장',short:'동물 농장',emoji:'🌻',color:'#f5efcb',ink:'#8a7c31',desc:'오늘은 무슨 열매가 열렸을까'},
 {id:7,name:'꼬마 용의 마법 성',short:'마법의 성',emoji:'🏰',color:'#e7ddf9',ink:'#80649f',desc:'꼬마 용이 건네는 초대장'},
 {id:8,name:'펭귄의 눈꽃 마을',short:'눈꽃 마을',emoji:'🐧',color:'#deedf6',ink:'#5687a7',desc:'눈송이 속에서 찾는 따뜻함'},
 {id:9,name:'가을 숲 캠핑',short:'가을 캠핑',emoji:'🏕️',color:'#fae3cd',ink:'#9f673d',desc:'모닥불 옆에 모인 친구들'},
 {id:10,name:'장난감 자동차 마을',short:'장난감 마을',emoji:'🚂',color:'#dcecdf',ink:'#4b8068',desc:'칙칙폭폭, 신나는 하루'},
 {id:11,name:'두근두근 보물섬',short:'비밀 보물섬',emoji:'🏝️',color:'#d8f0e7',ink:'#3f8578',desc:'우리만의 보물을 찾아서'}
];
export const MODES={relax:{name:'느긋하게',icon:'☁',desc:'시간 제한 없이 찬찬히',seconds:0,hearts:0},adventure:{name:'모험 모드',icon:'⚑',desc:'시간 안에 다섯 곳 찾기',seconds:150,hearts:5},challenge:{name:'챌린지',icon:'ϟ',desc:'90초, 하트 3개로 도전',seconds:90,hearts:3}};
export function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export function seeded(seed){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^t>>>15,t|1);r^=r+Math.imul(r^r>>>7,r|61);return((r^r>>>14)>>>0)/4294967296}}
export function dailyLevels(date=dateKey()){const seed=[...date].reduce((s,c)=>s*31+c.charCodeAt(0),0);const rng=seeded(seed);const a=[];while(a.length<3){const n=Math.floor(rng()*108);if(!a.includes(n))a.push(n)}return a}
export function emptySave(){return {version:1,coins:60,records:{},settings:{sound:true,vibration:true,motion:true},daily:{date:dateKey(),wins:0,finds:0,noHint:0,claimed:[],dailyWon:false,checkin:false},totals:{finds:0,wins:0,perfect:0,noHint:0,combo:0},lastLevel:0,mode:'relax',badges:[],history:[]}}
export function normalizeSave(raw){const s=emptySave();if(!raw||raw.version!==1)return s;s.coins=Number.isFinite(raw.coins)?Math.max(0,Math.min(1e7,Math.floor(raw.coins))):60;s.lastLevel=Number.isInteger(raw.lastLevel)&&raw.lastLevel>=0&&raw.lastLevel<108?raw.lastLevel:0;s.mode=MODES[raw.mode]?raw.mode:'relax';for(const key of Object.keys(s.settings))if(typeof raw.settings?.[key]==='boolean')s.settings[key]=raw.settings[key];for(const key of Object.keys(s.totals))s.totals[key]=Number.isFinite(Number(raw.totals?.[key]))?Math.max(0,Math.floor(Number(raw.totals[key]))):0;if(raw.records&&typeof raw.records==='object')for(const [k,r]of Object.entries(raw.records)){if(!/^\d+$/.test(k)||Number(k)>=108||!r||!Number.isFinite(r.stars))continue;s.records[k]={stars:Math.min(3,Math.max(1,Math.round(r.stars))),score:Math.max(0,Number(r.score)||0),time:Math.max(0,Number(r.time)||0)}}if(raw.daily?.date===dateKey()){for(const k of ['wins','finds','noHint'])s.daily[k]=Number.isFinite(Number(raw.daily[k]))?Math.max(0,Math.floor(Number(raw.daily[k]))):0;for(const k of ['dailyWon','checkin'])s.daily[k]=raw.daily[k]===true;s.daily.claimed=Array.isArray(raw.daily.claimed)?[...new Set(raw.daily.claimed.filter(x=>['wins','finds','noHint'].includes(x)))]:[];}s.badges=Array.isArray(raw.badges)?raw.badges.filter(x=>typeof x==='string'):[];s.history=Array.isArray(raw.history)?raw.history.filter(r=>r&&Number.isInteger(r.level)&&r.level>=0&&r.level<108&&MODES[r.mode]&&Number.isFinite(r.score)&&typeof r.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(r.date)).slice(0,20):[];return s}
export function loadSave(storage){try{return normalizeSave(JSON.parse((storage??globalThis.localStorage).getItem(SAVE_KEY)))}catch{return emptySave()}}
export function freshDay(save){if(save.daily.date!==dateKey())save.daily=emptySave().daily;return save}
export function starsFor({mistakes,hints}){return mistakes===0&&hints===0?3:mistakes<=2&&hints<=2?2:1}
export function levelUnlocked(id,save){return id%9===0||Boolean(save.records[id-1])||Boolean(save.records[id])}
export function worldStars(id,save){return Array.from({length:9},(_,i)=>save.records[id*9+i]?.stars||0).reduce((a,b)=>a+b,0)}
export function hitTarget(targets,x,y,found=[],tolerance=.018){return targets.find(t=>!found.includes(t.id)&&Math.hypot(x-t.x,y-t.y)<=t.r+tolerance)||null}
export function award(save,result){freshDay(save);const old=save.records[result.level];const stars=starsFor(result);const improvement=Math.max(0,stars-(old?.stars||0));const coins=old?8+improvement*8:25+stars*8;save.coins+=coins;save.records[result.level]={stars:Math.max(stars,old?.stars||0),score:Math.max(result.score,old?.score||0),time:old?Math.min(old.time,result.elapsed):result.elapsed};save.totals.wins++;save.totals.perfect+=stars===3?1:0;save.totals.noHint+=result.hints===0?1:0;save.totals.combo=Math.max(save.totals.combo,result.maxCombo);save.daily.wins++;save.daily.noHint+=result.hints===0?1:0;save.lastLevel=Math.min(107,result.level+1);save.history.unshift({level:result.level,score:result.score,mode:result.mode,date:dateKey()});save.history=save.history.slice(0,20);return{stars,coins,first:!old}}
export const BADGES=[{id:'first',name:'첫 번째 발견',emoji:'🔎',desc:'첫 스테이지 완료',check:s=>s.totals.wins>=1},{id:'ten',name:'단골 탐정',emoji:'🎒',desc:'스테이지 10번 완료',check:s=>s.totals.wins>=10},{id:'sharp',name:'매의 눈',emoji:'🦉',desc:'힌트 없이 5번 완료',check:s=>s.totals.noHint>=5},{id:'perfect',name:'반짝반짝',emoji:'✨',desc:'별 3개로 5번 완료',check:s=>s.totals.perfect>=5},{id:'combo',name:'번개 탐정',emoji:'⚡',desc:'5콤보 달성',check:s=>s.totals.combo>=5},{id:'hundred',name:'발견 수집가',emoji:'💎',desc:'차이 100개 발견',check:s=>s.totals.finds>=100},{id:'globe',name:'세계 여행자',emoji:'🌏',desc:'12개 테마에서 하나씩 완료',check:s=>THEMES.every(t=>Object.keys(s.records).some(n=>Math.floor(Number(n)/9)===t.id))},{id:'master',name:'전설의 탐정',emoji:'🏆',desc:'108개 스테이지 모두 완료',check:s=>Object.keys(s.records).length===108}];
