/** Deterministic game-content compiler: atlas tiles → pairs + exact hit regions.
 * Runtime game effects recolor connected pigment regions; original generated art stays intact.
 * Run: node scripts/build-scenes.mjs /absolute/path/to/game-art
 * Uses sharp from `npm install --no-save sharp` or CODEX_PRIMARY_RUNTIME_NODE_MODULES.
 */
import fs from 'node:fs/promises';import path from 'node:path';import{createRequire}from'node:module';import{seeded}from'../core.js';
const req=createRequire(import.meta.url);let sharp;try{sharp=req('sharp')}catch{sharp=req(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||'', 'sharp'))}
const src=path.resolve(process.argv[2]||'../game-art'),out=path.resolve('assets/scenes');await fs.mkdir(out,{recursive:true});const manifest=[];const report=[];
function hsv(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return[h,max?d/max:0,max]}
function rgb(h,s,v){h=((h%360)+360)%360;const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let z=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return z.map(n=>Math.round((n+m)*255))}
function regions(data,w,h,seed,hueStep=30,valueBins=0,compact=.52){const q=new Int16Array(w*h).fill(-1),visited=new Uint8Array(w*h),rng=seeded(seed);for(let i=0;i<w*h;i++){const [hu,s,v]=hsv(...data.subarray(i*3,i*3+3));if(s>.30&&v>.28)q[i]=Math.floor(hu/hueStep)+Math.floor(v*valueBins)*30}
const all=[];for(let st=0;st<w*h;st++){if(visited[st]||q[st]<0)continue;const col=q[st],stack=[st],pix=[];visited[st]=1;let minX=w,minY=h,maxX=0,maxY=0,sx=0,sy=0;for(let k=0;k<stack.length;k++){const n=stack[k],x=n%w,y=Math.floor(n/w);pix.push(n);sx+=x;sy+=y;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);const nn=[];if(x>0)nn.push(n-1);if(x<w-1)nn.push(n+1);if(y>0)nn.push(n-w);if(y<h-1)nn.push(n+w);for(const m of nn)if(!visited[m]&&q[m]===col){visited[m]=1;stack.push(m)}}const area=pix.length,bw=maxX-minX+1,bh=maxY-minY+1;if(area<70||area>w*h*.08||bw<9||bh<9||bw>w*.36||bh>h*.36||area/(bw*bh)<compact||minX<4||minY<4||maxX>w-5||maxY>h-5)continue;const cx=(minX+maxX)/2,cy=(minY+maxY)/2,r=Math.hypot(bw,bh)/2+2;if(r>w*.18)continue;all.push({pix,minX,minY,maxX,maxY,cx,cy,r,score:Math.sqrt(area)*(0.8+rng()*.4)})}
all.sort((a,b)=>b.score-a.score);let best=[];for(let attempt=0;attempt<40;attempt++){const order=attempt===0?all:[...all].sort((a,b)=>b.score*(.4+rng())-a.score*(.4+rng()));const chosen=[];for(const c of order){if(chosen.every(o=>Math.hypot(c.cx-o.cx,c.cy-o.cy)>c.r+o.r+3))chosen.push(c);if(chosen.length===5)break}if(chosen.length>best.length)best=chosen;if(best.length===5)break}return {selected:best,candidateCount:all.length}}
for(let theme=1;theme<=12;theme++){let bytes;try{bytes=await fs.readFile(path.join(src,`atlas-${String(theme).padStart(2,'0')}.png`))}catch{console.log(`Waiting for atlas ${theme}; compile ready themes only.`);break}const meta=await sharp(bytes).metadata();if(meta.width!==meta.height||meta.width%3)throw Error('Atlas must be exact square3x3');const step=meta.width/3;for(let tile=0;tile<9;tile++){const id=(theme-1)*9+tile,base=String(id+1).padStart(3,'0');const crop=await sharp(bytes).extract({left:(tile%3)*step+2,top:Math.floor(tile/3)*step+2,width:step-4,height:step-4}).resize(512,512,{kernel:'lanczos3'}).removeAlpha().raw().toBuffer();const small=await sharp(crop,{raw:{width:512,height:512,channels:3}}).resize(192,192).blur(1.2).raw().toBuffer();let selected=[],candidateCount=0;for(const compact of [.52,.44,.35]){for(const [hs,vb]of [[30,0],[30,2],[45,3],[20,3],[20,4],[60,3]]){const attempt=regions(small,192,192,1999+id*97,hs,vb,compact);if(attempt.selected.length>selected.length){selected=attempt.selected;candidateCount=attempt.candidateCount}if(selected.length===5)break}if(selected.length===5)break}if(selected.length!==5)throw Error(`Scene ${base}: only${selected.length}/5 distinct valid regions from${candidateCount} candidates`);const variant=Buffer.from(crop),targets=[];selected.forEach((r,index)=>{const mask=new Uint8Array(192*192);for(const p of r.pix)mask[p]=1;let changed=0,sumDelta=0;for(let y=Math.floor(r.minY/192*512);y<=Math.ceil((r.maxY+1)/192*512);y++){for(let x=Math.floor(r.minX/192*512);x<=Math.ceil((r.maxX+1)/192*512);x++){const fx=x/512*192-.5,fy=y/512*192-.5,xx=Math.max(0,Math.min(190,Math.floor(fx))),yy=Math.max(0,Math.min(190,Math.floor(fy))),dx=fx-Math.floor(fx),dy=fy-Math.floor(fy);const alpha=mask[yy*192+xx]*(1-dx)*(1-dy)+mask[yy*192+xx+1]*dx*(1-dy)+mask[(yy+1)*192+xx]*(1-dx)*dy+mask[(yy+1)*192+xx+1]*dx*dy;if(alpha<.03)continue;const p=(y*512+x)*3;if(p>=variant.length)continue;const old=[crop[p],crop[p+1],crop[p+2]],[hu,s,v]=hsv(...old);const shift=[135,180,95,225,160][(id+index)%5];let newColor=rgb(hu+shift,Math.min(1,s*1.15+.10),Math.min(.96,Math.max(.27,v*.88+.07)));if(index===4&&Math.floor((x+y)/10)%2===0)newColor=newColor.map(c=>Math.round(c*.70));for(let c=0;c<3;c++){sumDelta+=Math.abs(old[c]-newColor[c]);variant[p+c]=Math.round(old[c]*(1-alpha)+newColor[c]*alpha)}changed++}}const t={id:index+1,x:(r.cx+.5)/192,y:(r.cy+.5)/192,r:r.r/192,bounds:[r.minX/192,r.minY/192,(r.maxX+1)/192,(r.maxY+1)/192],kind:index===4?'pattern':'color',changedPixels:changed,meanDelta:Math.round(sumDelta/Math.max(1,changed*3))};if(changed<400||t.meanDelta<18)throw Error(`Scene ${base}: effect too weak ${JSON.stringify(t)}`);targets.push(t)});
// Encode lossless so paired images differ only at selected target masks, never codec noise.
await sharp(crop,{raw:{width:512,height:512,channels:3}}).webp({lossless:true,effort:4}).toFile(path.join(out,`${base}-a.webp`));await sharp(variant,{raw:{width:512,height:512,channels:3}}).webp({lossless:true,effort:4}).toFile(path.join(out,`${base}-b.webp`));manifest.push({id,world:theme-1,stage:tile+1,source:`atlas-${String(theme).padStart(2,'0')}.png#${tile}`,targets});report.push({id:id+1,candidates:candidateCount,targets:targets.length,changedPixels:targets.reduce((a,t)=>a+t.changedPixels,0)});}console.log(`World ${theme} compiled: ${manifest.length} distinct scenes / ${manifest.length*2} images`)}
await fs.writeFile('assets/levels.json',JSON.stringify(manifest));await fs.writeFile('assets/validation.json',JSON.stringify({algorithmVersion:1,originalScenes:manifest.length,imageFiles:manifest.length*2,differences:manifest.length*5,report},null,2));console.log(`DONE ${manifest.length} levels.`);
